name: flash_blog
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  desktop_window: ^0.4.2
  internet_connection_checker_plus: ^2.7.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_gen_runner: ^5.3.1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^14.7.2
  hive: ^2.2.3
  riverpod_annotation: ^2.6.1
  json_serializable: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.0
  go_router_builder: ^2.8.2
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5


flutter:
  uses-material-design: true
